### ISSUE TITLE
Finish implementing Bailey's designs

### ISSUE THREAD

**Issue by colinxfleming** [AbortionAccessHackathon/noaf_site#10]

**Comment by colinxfleming** [comment]
This probably includes some confirmation that it renders ok on mobile

**Comment by cruellachivil** [comment]
On the mobile side of things, let's QA the nav bar/menu (right now it appears to be hidden - we may need to fix some setting on squarespace)

**Comment by colinxfleming** [comment]
Bailey's designs are implemented to the best of our ability, and I've shut off the mobile mode for simplicity's sake. Marking closed.
